version: "3.9"
services:
  rtchat-db:
    image: postgres
    restart: always
    container_name: rtchat-db
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
